development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://redistogo:e95b89e6821cb07eb2e5a1b09d1bce8f@pike.redistogo.com:9549/" } %>
  channel_prefix: Demo_production
